# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
Ad1.create!([
  {review: "The quality of the product is below average.", response: "Quality"},
  {review: "The quality of the product is below average.", response: "Quality"},
  {review: "The quality of the product is below average.", response: "Quality"},
  {review: "The quality of the product is below average.", response: "Quality"},
  {review: "The quality of the product is below average.", response: "Quality"},
  {review: "The quality of the product is below average.", response: "Quality"}
])
Tmpl.create!([
  {intent: "spam", Gtemp: ["We have noticed that your review is categorized as spam. We at $COMPANY_NAME take our reviews very seriously and work very hard to ensure the full satisfaction of our customers. Further, spam reviews lead to disappointment from our customers who are looking for genuine products and hence we request you to delete it immediately."], Ptemp: []},
  {intent: "quality", Gtemp: ["We want to extend our sincerest apologies concerning all the issues that you have faced. We pride ourselves in maintaining the highest quality standards for our customers. So, we hope you will grant us an opportunity to discuss this further with you."], Ptemp: ["We're extremely sorry that you had to face such difficulties, problems in customer service is not something we are known for. As you can see from our other reviews, we pride ourselves in providing great customer service and we'd like to do the same for you. We may not be able to change the past but if you give us a chance, we will completely make it up to you. Our GM, Mr. Jack Stoke will be reaching out to you personally. We hope to resolve this to your benefit and earn you back as a customer. { customer service related }", "We would be very much obliged to send you a replacement or offer you a full refund of the product, it’s your choice! { not functional }", "Sorry for the inconveniences caused by our product. However, we can get it replaced in a day’s time as your product is still under our care by warranty! { warranty }"]},
  {intent: "delivery", Gtemp: ["We are normally known for our on-time delivery and excellent customer care services and we deeply regret that we’ve missed our mark for you."], Ptemp: ["We are in constant touch with the courier service provider to get this issue sorted. Our team should revert back to you within a day’s time. { not delivered }", "-> We’d like to apologize for the problems you had to face due to the delivery personnel. We take our customer delivery satisfaction very strictly and have placed an investigation request on the responsible people. We will work to assure you a very courteous service here-on after. { if delivery person is rude }", "We have raised an issue with the courier service provider and our internal dispatch team to identify the root cause to your problem. We will revert back to you at the earliest with your status as we value your concerns highly. { late delivery }"]},
  {intent: "packaging", Gtemp: ["We at $COMPANY_NAME ensure stringent packaging quality for all our most respected customers such that the package withstands even extreme conditions. We are dedicated to ensuring that you have a seamless and worry-free experience shopping with us! "], Ptemp: ["We are deeply saddened to know that our packaging was damaged upon receiving. To compensate for your loss, we offer you a complete replacement of the product or a total refund. All with no questions asked! { damaged packaging and product }", "We understand that you had certain problems unpacking our product as the packaging was too tiresome. However, to ensure that our product reaches you safe and sound, we implement stringent packaging measures. To compensate for your troubles, we would like to offer you an exclusive $OFFER as a kind gesture from our side. We hope to win your favor with all our hard work! { problems unpacking }"]},
  {intent: "price", Gtemp: ["We understand that you have concerns regarding the price of our product. We are most obliged to solve your queries and concerns as we value our customers a lot and are very dedicated to ensuring them the best of services available. "], Ptemp: ["-> We at $COMPANY_NAME have ensured that our products are always worth their price and are always of the best value. I would like to offer you an exclusive $OFFER on your next purchase with us as a token of good will! We hope to win you back as one of your most beloved customers! { High priced } ", "-> We understand that you do not find our product to be of value for the price paid. $COMPANY_NAME aims to offer the highest value in our services offered and deeply regret your experience with our product. Our product consumer team will get in touch with you very shortly and converse regarding the same. We humbly ask of you to share your problems to them as they are very much dedicated to solving all of our customers problems and will do it without any hassles! { No value for price } "]}
])
